# FlowScan3 主配置
redis:
  listen_host: 0.0.0.0
  remote_host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

web_config:
  host: 0.0.0.0
  port: 8080
  username: FlowScan
  password: FlowScanPassWord123
  session_ttl: 3600
  secret_key: 5329a77d233311276c3f0ac7951b165c0b43fdfe9b7e1226abaa603da135a22d


xray_listen_http_proxy: 0.0.0.0:7777
xray_remote_http_proxy: http://127.0.0.1:7777

worker:
  idle_sleep_seconds: 1.0
  scan_batch_size: 200
  max_local_pending: 40
  
bbot:
  port_range: 1-65535
  securitytrails_api_key: 
  virustotal_api_key: 
  github_workflows_api_key: 

fofa:
  api_key: YOUR_FOFA_API_KEY
  base_url: https://fofa.info



ai_analysis:
  base_url: https://api.openai.com/v1
  api_key: YOUR_OPENAI_COMPATIBLE_API_KEY
  model: gpt-4o-mini
  timeout_seconds: 120
  max_events: 200
  # system_prompt 未设置时自动从 prompts/ai_analysis.txt 读取
  # system_prompt: |
  #   自定义提示词（覆盖 prompts/ai_analysis.txt）
  log_api_key: d6de3f6386d67953484daea7d560e8c97227bfac55f31ec628c837b2939d3fc0
  loop_interval_minutes: 0
